Homework #View & ViewGroups
dakosonogov/AwesomeMovie pull request #1
Opened 2020-11-23 10:31 UTC by dakosonogov

Try to make pull request

2020-11-23 23:26 UTC, Vladuken requested changes
Проверил

Кроме комментариев, у тебя очень сильно сжаты webp -настолько, что видно невооруженным взглядом. 
Также mask.png ты можешь из фирмы достать svg и импортировать.

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:drawableLeftCompat="@drawable/ic_arrow_back"
drawableStartCompat

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:background="@color/bg_age_rating"
тут бэкграунд с закругленными углами, а не просто цвет

Лучше или просто оставить прозрачной вьюху, либо добавить бэкграунд с закругленными углами (это через xml делается )

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_width="wrap_content"
Как мне кажется, лучше добавить констрейнты end to end и установить ширину в 0dp

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:lines="2"
из-за этой строчки, если мы увеличим текст в настройках устройства, тексту может понадобиться 3 строки, а оно не влезет

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:lines="2"
Плюс: lines - указывает на то, что у textview будет всегда выделено место под 2 линии текста, даже если у нас текста хватает лишь на одну линию.

Для более динамической верстки можешь попробовать maxLines="2". Тогда если строка будет помещаться одну линию, места будет на 1 линию выделено, а не на две.

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_width="wrap_content"
тоже сделай 0 dp и расставь констрейнт к концу

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:minHeight="14dp"
кажется тут wrap content будет достаточно и minHeight тут не нужно (плюс заметил сейчас что в style/CustomRatingBar есть dip, лучше dp, но можно и просто удалить minHeight )

2020-11-23 23:26 UTC, Vladuken commented on app/src/main/res/drawable/custom_rating_bar.xml
> +    <item
мне кажется можно удалить первый или второй item из layerlist-a

2020-11-24 22:15 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +        <androidx.constraintlayout.widget.Guideline
Забираю свои слова обратно - с паддингами картинка header-а поедет
А гайдлайны позволяют убрать вложенность, так что можешь верхний комментарий игнорировать)

2020-11-25 12:32 UTC, dakosonogov commented on app/src/main/res/drawable/colored_star.xml
> +    <item android:drawable="@drawable/ic_colored_star" android:state_pressed="true" android:state_window_focused="true"/>
Брал отсюда - http://developer.alexanderklimov.ru/android/views/ratingbar.php Т.к. в итоге закастомизировать не получилось оставил как есть, до сих пор не понимаю, почему не сработало заменить звездочки

2020-11-25 12:33 UTC, dakosonogov commented on app/src/main/res/drawable/ic_arrow_back.xml
> +      android:fillColor="#6D6D80"/>
Ок, но я через импорт svg это делал и дальше внутрь xml уже не лез. Поменял

2020-11-25 12:39 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_width="wrap_content"
Cделал

2020-11-25 12:40 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:lines="2"
Сделал

2020-11-25 12:41 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_width="wrap_content"
Сделал

2020-11-25 12:41 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:minHeight="14dp"
Удалил, но я просто намучился с неудавшейся кастомизацией рейтинг бара. Делал все рецепты что мог найти в сети

2020-11-25 12:42 UTC, dakosonogov commented on app/src/main/res/drawable/custom_rating_bar.xml
> +    <item
Пробовал ничего не помогло, в итоге просто стилями цвет поменял

2020-11-25 12:42 UTC, dakosonogov commented on app/src/main/java/ru/kosonogov/awesomemovie/MainActivity.kt
> +        val button: Button = findViewById(R.id.button)
Сделал через ViewBinding

2020-11-25 12:43 UTC, dakosonogov commented on app/src/main/AndroidManifest.xml
> +        </activity>
Когда тестил, делал чтобы эта активити запускалась при старте, забыл исправить.

2020-11-25 12:44 UTC, dakosonogov commented on app/src/main/java/ru/kosonogov/awesomemovie/MovieDetailsActivity.kt
> +        setContentView(R.layout.activity_movie_details)
Сделал через ViewBinding

2020-11-25 20:14 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:lines="2"
Предлагаю вообще убрать maxLines, чтобы если вьюшке понадобится 3 строчки, она заняла их.

Либо можно использовать maxLines и ellipsize атрибуты у вьюхи, тогда у тебя будет выглядеть вьюха как 
"Chris 
Hemsw..."
 То есть заполняться точками в конце если места будет не хватать.

Выбери тот вариант который тебе удобнее

2020-11-25 20:17 UTC, Vladuken commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:minHeight="14dp"
Поправь еще dip на dp в themes.xml

2020-11-26 19:22 UTC, dakosonogov commented on app/src/main/res/drawable/ic_colored_star.xml
> +      android:fillColor="#FF3365"
Fix

2020-11-26 19:22 UTC, dakosonogov commented on app/src/main/res/drawable/ic_non_colored_star.xml
> +  </group>
Fix

2020-11-26 19:22 UTC, dakosonogov commented on app/src/main/res/drawable/ic_non_colored_star.xml
> +      android:fillColor="#6D6D80"
Fix

2020-11-26 19:23 UTC, dakosonogov commented on app/src/main/res/drawable/non_colored_star.xml
> +    <item android:drawable="@drawable/ic_non_colored_star" android:state_pressed="true" android:state_window_focused="true"/>
Fix цвет, остальные пока оставил, чтобы потом попробовать все-таки кастомную звездочку прикрутить

2020-11-26 19:24 UTC, dakosonogov commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.5"
Убрал, я для кнопки констрейнты не руками делал, а с помощью кнопки в android studio, которая горизонтальный и вертикальный констреинты добавляет, она почему-то и это свойство добавила.

2020-11-26 19:24 UTC, dakosonogov commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Button"
Fix

2020-11-26 19:24 UTC, dakosonogov commented on app/src/main/res/values/strings.xml
> +    <string name="back">Back</string>
Переименовал

2020-11-26 19:25 UTC, dakosonogov commented on app/src/main/res/values/themes.xml
> +        <item name="android:layout_width">0dp</item>
Вынес

2020-11-26 19:25 UTC, dakosonogov commented on app/src/main/res/values/themes.xml
> +        <item name="android:layout_marginTop">14dp</item>
Вынес

2020-11-26 19:25 UTC, dakosonogov commented on build.gradle
> +        classpath "com.android.tools.build:gradle:4.1.0"
Обновил

2020-11-26 19:31 UTC, dakosonogov commented on app/src/main/res/layout-land/activity_movie_details.xml
> +<?xml version="1.0" encoding="utf-8"?>
Удалил

2020-11-26 19:31 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:id="@+id/movie_banner"
Ок, подумаю, пока решил оставить так.

2020-11-26 19:31 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_width="match_parent"
Fix

2020-11-26 19:31 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:drawableLeftCompat="@drawable/ic_arrow_back"
Fix

2020-11-26 19:32 UTC, dakosonogov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:background="@color/bg_age_rating"
Удалил фон

2020-11-26 23:27 UTC, Vladuken commented on app/src/main/res/drawable/ic_non_colored_star.xml
> +  </group>
Я подразумевал тег вместе с его содержимым

Вот это тоже можно удалить
<img width="804" alt="image" src="https://user-images.githubusercontent.com/23121846/100396875-02f81480-3058-11eb-866a-d31128f7f0db.png">

2020-11-28 13:10 UTC, merged